# Generated by Django 3.2.8 on 2021-12-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20211116_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTask',
            fields=[
                ('idAssignedTask', models.AutoField(primary_key=True, serialize=False)),
                ('idTask', models.IntegerField()),
                ('idStudent', models.IntegerField()),
                ('idEducator', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('assignedDate', models.DateField()),
                ('completedDate', models.DateField()),
                ('completed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ClassMenu',
            fields=[
                ('idClassMenu', models.AutoField(primary_key=True, serialize=False)),
                ('idEducator', models.IntegerField()),
                ('date', models.DateField()),
                ('numNormalMenu', models.IntegerField()),
                ('numNoMeatMenu', models.IntegerField()),
                ('numCrushedMenu', models.IntegerField()),
                ('numDessertFruit', models.IntegerField()),
                ('numDessertCrushedFruit', models.IntegerField()),
                ('numDessertYogurtCustard', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DinningTask',
            fields=[
                ('idDinningTask', models.AutoField(primary_key=True, serialize=False)),
                ('classes', models.CharField(default='test', max_length=250)),
                ('menus', models.CharField(default='test', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='StockTask',
            fields=[
                ('idStockTask', models.AutoField(primary_key=True, serialize=False)),
                ('place', models.CharField(default='test', max_length=50)),
                ('pictogramPlace', models.CharField(default='test', max_length=100)),
                ('quantity', models.IntegerField()),
                ('pictogramQuantity', models.CharField(default='test', max_length=100)),
                ('material', models.CharField(default='test', max_length=50)),
                ('pictogramMaterial', models.CharField(default='test', max_length=100)),
                ('idStudent', models.IntegerField()),
                ('idEducator', models.IntegerField()),
                ('priority', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Assigned',
            new_name='AssignedStudent',
        ),
        migrations.RenameField(
            model_name='admin',
            old_name='adminId',
            new_name='idAdmin',
        ),
        migrations.RenameField(
            model_name='assignedstudent',
            old_name='assignedId',
            new_name='idAssignedStudent',
        ),
        migrations.RenameField(
            model_name='assignedstudent',
            old_name='studentId',
            new_name='idEducator',
        ),
        migrations.RenameField(
            model_name='assignedstudent',
            old_name='taskId',
            new_name='idStudent',
        ),
        migrations.RenameField(
            model_name='educator',
            old_name='educatorId',
            new_name='idEducator',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='accesibilityType',
            new_name='accessibilityType',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='studentId',
            new_name='idStudent',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='taskId',
            new_name='idTask',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='educator',
            name='userName',
        ),
        migrations.RemoveField(
            model_name='task',
            name='finished',
        ),
        migrations.RemoveField(
            model_name='task',
            name='taskDate',
        ),
        migrations.AddField(
            model_name='admin',
            name='email',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='educator',
            name='email',
            field=models.CharField(default='test', max_length=50),
        ),
        migrations.AddField(
            model_name='educator',
            name='picture',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='picture',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='pictogramDescription',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='pictogramTitle',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='admin',
            name='password',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='educator',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='educator',
            name='password',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='test', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.CharField(default='test', max_length=250),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(default='test', max_length=50),
        ),
    ]
