# Generated by Django 3.2.8 on 2021-12-15 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211208_1102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinningtask',
            name='classes',
        ),
        migrations.RemoveField(
            model_name='dinningtask',
            name='menus',
        ),
        migrations.AddField(
            model_name='dinningtask',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dinningtask',
            name='idStudent',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
