version: "3.9"
   
services:
  web:
    build: .
    command: bash -c "python -m pip install django-cors-headers && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"